<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function robco_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.robco_rest':
      return t('
        <h2>RobCo integration of drupal and redmine</h2>
        <h3>Instructions</h3>
        <p>This module provides integration of <strong>Drupal</strong> and <strong>Redmine</strong></p>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/development/loremipsum</strong> and enter your own set of phrases to build random-generated text (or go with the default Lorem ipsum).</p>
        <p>Last, visit <strong>www.example.com/loremipsum/generate/P/S</strong> where:</p>
        <ul>
          <li><em>P</em> is the number of <em>paragraphs</em></li>
          <li><em>S</em> is the maximum number of <em>sentences</em></li>
        </ul>
        <p>There is also a generator block in which you can choose how many paragraphs and
phrases and it\'ll do the rest.</p>
        <p>If you need, there\'s also a specific <em>generate lorem ipsum</em> permission.</p>
        <h3>Attention</h3>
        <p>Most bugs have been ironed out, holes covered, features added. But this module is a work in progress. Please report bugs and suggestions, ok?</p>
      ');
  }
}


/**
 * Implements hook_views_data().
 */
/*function custom_module_views_data() {
  $data['views']['table']['group'] = t('Custom Global');
  $data['views']['table']['join'] = [
    // #global is a special flag which allows a table to appear all the time.
    '#global' => [],
  ];

  $data['views']['add_to_cart_views_field'] = [
    'title' => t('Add to cart'),
    'help' => t('Place product in the cart.'),
    'field' => [
      'id' => 'add_to_cart_views_field',
    ],
  ];
  
  $data['views']['remove_from_cart_views_field'] = [
    'title' => t('Remove cart'),
    'help' => t('Remove product from the cart.'),
    'field' => [
      'id' => 'remove_from_cart_views_field',
    ],
  ];
  
  return $data;
}*/
