robco_rest.settings:
  type: config_object
  label: 'RobCo REST API settings'
  mapping:
    robco_rest:
      type: mapping
      mapping:
        host:
          type: text
          label: 'REST Host:'
        api_key:
          type: text
          label: 'API key:'
        commerce_project_id:
          type: text
          label: 'Commerce project ID'
        anonymous_user_id:
          type: text
          label: 'Redmine ID of anonymous cart owner'
